name: Upload Artifact

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a file
      run: echo "i have all your base" > sample.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sample-artifact
        path: sample.txt
