name: Upload Artifact

on: [pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create a file
      run: echo "and I can do whatever I want" > sample.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: sample-artifact
        path: sample.txt
